version: "3.8"

services:
  next-compiled:
    build:
      context: ../..  # This should be set to two levels up from where the Dockerfile is, if that's where the folders you want to copy are located.
      dockerfile: apps/next-compiled/Dockerfile 
    entrypoint: "yarn prod-standalone"
    environment:
      - PROXY_API_URL=http://admin-api:8080
      - NODE_ENV=production