version: '3'
services:
  builder:
    image: "protofy/workspace"
    container_name: builder
    entrypoint: "sh -c 'npm run prepare-dev && yarn && yarn build'"
    volumes:
      - ./:/workspace
      - node_modules:/workspace/node_modules

volumes:
  node_modules: