services:
  admin-api:
    container_name: 'admin-api'
    image: "protofy/workspace"
    entrypoint: "yarn admin-api-prod"
    environment:
      - MQTT_URL=mqtt://localhost:8883
    volumes:
      - ../../data:/workspace/data