version: '3.8'

services:
  admin-api:
    image: "protofy/workspace"
    entrypoint: "sh -c 'cd apps/admin-api && yarn dev-standalone'"
    ports:
      - 3002:3002
      - 8080:8080
    environment:
      - MQTT_URL=mqtt://localhost:1883
      - PROXY_API_URL=http://admin-api:8080
      - ADMIN_API_URL=http://admin-api:3002
      - API_URL=http://api:3001
      - SITE_URL=http://site:3000
      - ADMIN_SITE_URL=http://admin:3003 
      - DOCS_SITE_URL=http://docs:7600
      - NODE_ENV=development
    volumes:
      - ../../:/workspace
      - protofy_modules:/workspace/node_modules
      
volumes:
  protofy_modules:
    external: true