services:
  proxy:
    image: "protofy/workspace"
    container_name: webserver-${PROJECT_NAME}
    hostname: webserver-${PROJECT_NAME}
    entrypoint: "yarn proxy"
    environment:
      - API_URL=http://api:3001
      - SITE_URL=http://site:3000
      - PORT=80
    networks:
      proxy:
        aliases:
          - webserver-db-${PROJECT_NAME}
      default:
        aliases:
          - webserver-db-${PROJECT_NAME}
networks:
  proxy:
    external:
      name: proxy