services:
  proxy:
    container_name: 'proxy'
    image: "protofy/workspace"
    entrypoint: "yarn proxy"
    ports:
      - 8888:8080
    environment:
      - API_URL=http://api:3001
      - SITE_URL=http://site:3000
