services:
  api:
    depends_on: 
      - admin-api
    container_name: 'api'
    image: "protofy/workspace"
    entrypoint: "yarn api-prod"
    environment:
      - MQTT_URL=mqtt://admin-api:8883
    volumes:
      - ../../data:/workspace/data