name: Daily Multi-OS Job

on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 12:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, windows-latest, macos-12, macos-13]  # macOS versions for Monterey and Ventura respectively

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.4'
        cache: 'yarn'

    - name: Health check versions
      run: |
        node -v
        yarn -v

    - name: Install NodeJS dependencies
      run: yarn
    
    - name: Start "Protofy"
      run: node .github/scripts/start.js
    
    - name: Set result output
      id: set-result
      if: always()  # This step will run regardless of previous step's success/failure
      run:  echo "::set-output name=result::${{ matrix.os }}: ${{ job.status }}"

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: always()  # This ensures that the notification job runs whether the build job succeeds or fails
    steps:
    - name: Daily build Report
      uses: rjstone/discord-webhook-notify@v1
      with:
          severity: info
          details: Daily Build Succeeded!
          color: '#a600e0'
          avatarUrl: https://raw.githubusercontent.com/Protofy-xyz/Protofy/assets/protofito_purple.png
          description: |
            Event: Daily Build
            ubuntu-18.04: ${{ needs.build.outputs.ubuntu-18.04 }}
            ubuntu-20.04: ${{ needs.build.outputs.ubuntu-20.04 }}
            ubuntu-22.04: ${{ needs.build.outputs.ubuntu-22.04 }}
            windows-latest: ${{ needs.build.outputs.windows-latest }}
            macos-12: ${{ needs.build.outputs.macos-12 }}
            macos-13: ${{ needs.build.outputs.macos-13 }}

          footer: Daily report.
          text: Check daily report!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}