name: Daily Multi-OS Job

on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 12:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, windows-latest, macos-12, macos-13]  # macOS versions for Monterey and Ventura respectively

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.4'
        cache: 'yarn'

    - name: Health check versions
      run: |
        node -v
        yarn -v

    - name: Install NodeJS dependencies
      run: yarn
    
    - name: Start "Protofy"
      run: node .github/scripts/start.js
    
    - name: Save result # save result
      if: always()
      run: |
        echo "${{ matrix.os }}: ${{ job.status }}" >> ${{ runner.temp }}/result.txt

    - name: Upload result # upload saved result as artifact to be consumed at notify job
      uses: actions/upload-artifact@v2
      with:
        name: result-${{ matrix.os }}
        path: ${{ runner.temp }}/result.txt

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: always()  # This ensures that the notification job runs whether the build job succeeds or fails
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v2

    - name: Combine results
      id: combine-results
      run: |
        for result_dir in result-*; do
          if [ -d "$result_dir" ]; then
            cat "$result_dir/result.txt" >> combined_results.txt
          fi
        done
        echo "Combined results:"
        cat combined_results.txt
        echo "RESULTS=$(cat combined_results.txt | base64)" >> $GITHUB_ENV
    - name: Decode Results
      run: |
        echo "DECODED_RESULTS=$(echo $RESULTS | base64 --decode)" >> $GITHUB_ENV

    - name: Daily build Report
      uses: rjstone/discord-webhook-notify@v1
      env:
        DECODED_RESULTS: ${{ env.DECODED_RESULTS }}
      with:
          severity: info
          details: Daily Build Report!
          color: '#a600e0'
          avatarUrl: https://raw.githubusercontent.com/Protofy-xyz/Protofy/assets/protofito_purple.png
          description: |
            Event: Daily Build
            ${{ env.DECODED_RESULTS }}

          footer: Daily report.
          text: Check daily report!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}