name: Protofy CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js 20.4.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.4.x'
        cache: 'yarn'

    - name: Health check versions
      run: |
        node -v
        yarn -v

    - name: Install NodeJS dependencies
      run: yarn

    - name: Start "Protofy"
      run: node .github/scripts/start.js

    - name: Run tests
      run: sudo yarn test:all # need to be run as admin
    
    - name: Test Success
      uses: rjstone/discord-webhook-notify@v1
      if: success()
      with:
          severity: info
          details: Test Succeeded!
          username: ${{ github.event.pusher.name }}
          color: '#00e065'
          avatarUrl: https://raw.githubusercontent.com/Protofy-xyz/Protofy/assets/logo-protofy.png
          description: |
            **Event:** push
            **Repo:** Protofy-xyz/Protofy
            **Ref:** ${{ github.ref }}
            **Workflow:** ${{ github.workflow }}
            **Author:** ${{ github.event.head_commit.author.name }}
            **Committer:** ${{ github.event.head_commit.committer.name }}
            **Pusher:** ${{ github.event.pusher.name }}
            **Commit:** [${{ github.event.head_commit.id }}](${{ github.event.head_commit.url }})
            **Commit Message:** ${{ github.event.head_commit.message }}

          footer: Severity: Informational
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

    - name: Test Failure
      uses: rjstone/discord-webhook-notify@v1
      if: failure()
      with:
          severity: error
          details: Test Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

    - name: Test Cancelled
      uses: rjstone/discord-webhook-notify@v1
      if: cancelled()
      with:
          severity: warn
          details: Test Cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}