name: Testing workflow Protofy CI
on:
  workflow_dispatch: # This allows manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js 20.4.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.4.x'
        cache: 'yarn'

    - name: Health check versions
      run: |
        node -v
        yarn -v

    - name: Install NodeJS dependencies
      run: yarn

    - name: Start "Protofy"
      if: false # TODO delete this line
      run: node .github/scripts/start.js

    - name: Run tests # TODO: change test:global --> test:all
      run: sudo yarn test:global | tee ${{ runner.temp }}/tests.txt # need to be run as admin
    
    - name: Upload result # upload saved result as artifact to be consumed at notify job
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: ${{ runner.temp }}/tests.txt

  notify:
    runs-on: ubuntu-latest
    needs: test
    if: always()  # This ensures that the notify job runs whether the test job succeeds or fails
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3

    - name: Show file content
      run: node .github/scripts/retrieveTestsReport.js $(echo "$(pwd)/reports/tests.txt")
        